# Header
# Github link:
# https://github.com/litten/hexo-theme-yilia

menu:
  Home: /

# SubNav
subnav:
  github: "https://github.com/riccoqu"
  zhihu: "https://www.zhihu.com/people/qu-rui-kang/activities"
  weixin: "/images/WechatAddMe.jpeg"
  mail: "mailto:ricco.qu@outlook.com"
  bilibili: "https://space.bilibili.com/4903420/#/"
  #weibo: "#"
  #qq: "#"
  #rss: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #acfun: "#"
  #facebook: "#"
  #google: "#"
  #twitter: "#"
  #linkedin: "#"

rss: /atom.xml

root: /

# Content
# 文章太长，截断按钮文字
excerpt_link: false
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: 'More'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏type设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 1
reward_wording: 'Wish you a good day'
alipay: /images/AliPay.jpg
weixin: /images/WeChatPay.jpg

# 目录
# 目录设定：0-不显示目录； 1-文章对应的md文件里有toc:true属性，才有目录； 2-所有文章均显示目录
toc: 2
# 根据自己的习惯来设置，如果你的目录标题习惯有标号，置为true即可隐藏hexo重复的序号；否则置为false
toc_hide_index: true
# 目录为空时的提示
toc_empty_wording: '噢，找不到你点的东西了'
# 是否有快速回到顶部的按钮
top: true

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#头像url
avatar: https://m9ljmg.dm.files.1drv.com/y4myIgBgxG_YpCoXDfgFOdbfar6iSHd6nbo9TbicyE86PEtXOLB-zb38tq3vRYbJxh7edVXQliufIbS2Cll4I0unCxJ_qraNFIey_R0ugD-3izZ17CxLro6vdikP1MysKg8MZ8JvnS4jJCMLY2-ki8i46HJhjqGIAbfcMHp1E-fN_1pbZE6B4g2ZvkGfanBGkIjME0zei3SW4L6xYoczHbBNg?width=2391&height=2391&cropmode=none

#是否开启分享
share_jia: true

# 网易云跟帖
wangyiyun: true
# 畅言
changyan_appid: false
changyan_conf: false
# Disqus
disqus: false
# Gitment
gitment_owner: false    #你的 GitHub ID
gitment_repo: 'https://github.com/riccoqu/riccoqu.github.io.git'          #存储评论的 repo
gitment_oauth:
  client_id: '465967679d90e1b0b3cd'           #client ID
  client_secret: '090ae01603fca4e1fde4823a5569416122f97c7c'       #client secret

style:
  header: '#4298F5'
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

slider:
  showTags: true

smart_menu:
  innerArchive: 'All Archive'
  aboutme: 'About Me'

friends:

aboutme : 我后面会补上的！(๑•̀ㅂ•́)و✧
